spring:
  application:
    name: Chat4Me - API Gateway
app:
  feign:
    clients:
      auth-service:
        url: http://localhost:8081
        api:
          startLogin: /auth/start-login
          verifyOTP: /auth/verify-otp
          validateToken: /auth/validate-token
          extractUUID: /auth/extract-uuid
          refreshToken: /auth/refresh
          getUsers: /users
      messaging-service:
        url: http://localhost:8082
        api:
          getMessages: /messages
          newMessage: /messages

server:
  port: 8080